[project]
name = "slonogram"
version = "0.9.0"

dependencies = [
  "anyio >= 4.0, < 5.0",
]
# Soon this will become >= 3.12
requires-python = ">= 3.11"

[project.optional-dependencies]
aiohttp = ["aiohttp[speedups] >= 3.9.0, <= 4.0.0"]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

